services:
  mysql:
    image: mariadb:10.11
    container_name: pyradius-mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/logs:/var/log/mysql
    ports:
      - "127.0.0.1:3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  radius:
    build: .
    image: pyradius
    container_name: pyradius
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
      - "1812:1812/udp"
      - "1813:1813/udp"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
    environment:
      TZ: ${TZ}
    env_file:
      - .env
