services:
  radius:
    build: ./backend
    container_name: pyradius
    restart: always
    ports:
      - "80:8000"
      - "1812:1812/udp"
      - "1813:1813/udp"
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3
    environment:
      - SECRET_KEY=django-insecure-dev-key-change-this-in-prod-custom
      - DEBUG=True
      - AUTH_PORT=1812
      - ACCT_PORT=1813
      - BIND_ADDRESS=0.0.0.0
      - LOG_LEVEL=DEBUG
      - ACCT_INTERIM_INTERVAL=60
      - RADIUS_INACTIVE_SESSION_DB_RETENTION_LIMIT=1000
      - RADIUS_LOG_RETENTION=1000
