services:
  radius:
    build: .
    image: pyradius
    container_name: pyradius
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "1812:1812/udp"
      - "1813:1813/udp"
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3
      - ./nginx/ssl:/etc/nginx/ssl
    env_file:
      - .env
